### ISSUE TITLE
build fail on manjaro

### ISSUE THREAD

**Issue by tree786** [hipiPan/GearEngine#3]
Ahoj

I have git clone the repo, and make a `build` folder. I then run this command:
```cmake .. &&     make -j8```
But I get build faile, with this error:
```
cmake 
/home/mm/Desktop/GearEngine/Engine/External/Blast/External/volk/volk.h:50:25: fatal error: vulkan/vulkan.h: No such file or directory
   50 | #               include <vulkan/vulkan.h>
      |                         ^~~~~~~~~~~~~~~~~

```
how i can solve? I am on manjaro (unix), and use GCC version 11.1.0

**Comment by hipiPan** [comment]
sorry, the Linux platform is not currently supported. and you should download vulkan sdk first.

**Comment by hipiPan** [comment]
https://vulkan.lunarg.com/

**Comment by tree786** [comment]
Ok thanks for info. I close this now
